// Generated by ReScript, PLEASE EDIT WITH CARE

import * as $$Set from "@rescript/std/lib/es6/set.js";
import * as Caml from "@rescript/std/lib/es6/caml.js";
import * as Format from "./Format.js";

function equal(x, y) {
  return x === y;
}

var compare = Caml.caml_int_compare;

var r = {
  contents: 0
};

function gen(param) {
  r.contents = r.contents + 1 | 0;
  return r.contents;
}

var $$Set$1 = $$Set.Make({
      compare: compare
    });

var pp = Format.pp_print_int;

export {
  equal ,
  compare ,
  gen ,
  pp ,
  $$Set$1 as $$Set,
  
}
/* Set Not a pure module */
