// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Pervasives from "@rescript/std/lib/es6/pervasives.js";

var List;

var Queue;

var invalid_arg = Pervasives.invalid_arg;

var failwith = Pervasives.failwith;

var Exit = Pervasives.Exit;

var abs = Pervasives.abs;

var max_int = Pervasives.max_int;

var min_int = Pervasives.min_int;

var lnot = Pervasives.lnot;

var infinity = Pervasives.infinity;

var neg_infinity = Pervasives.neg_infinity;

var max_float = Pervasives.max_float;

var min_float = Pervasives.min_float;

var epsilon_float = Pervasives.epsilon_float;

var classify_float = Pervasives.classify_float;

var char_of_int = Pervasives.char_of_int;

var string_of_bool = Pervasives.string_of_bool;

var bool_of_string = Pervasives.bool_of_string;

var bool_of_string_opt = Pervasives.bool_of_string_opt;

var int_of_string_opt = Pervasives.int_of_string_opt;

var string_of_float = Pervasives.string_of_float;

var float_of_string_opt = Pervasives.float_of_string_opt;

var $at = Pervasives.$at;

var stdin = Pervasives.stdin;

var stdout = Pervasives.stdout;

var stderr = Pervasives.stderr;

var print_char = Pervasives.print_char;

var print_string = Pervasives.print_string;

var print_bytes = Pervasives.print_bytes;

var print_int = Pervasives.print_int;

var print_float = Pervasives.print_float;

var print_newline = Pervasives.print_newline;

var prerr_char = Pervasives.prerr_char;

var prerr_string = Pervasives.prerr_string;

var prerr_bytes = Pervasives.prerr_bytes;

var prerr_int = Pervasives.prerr_int;

var prerr_float = Pervasives.prerr_float;

var prerr_newline = Pervasives.prerr_newline;

var read_line = Pervasives.read_line;

var read_int = Pervasives.read_int;

var read_int_opt = Pervasives.read_int_opt;

var read_float = Pervasives.read_float;

var read_float_opt = Pervasives.read_float_opt;

var open_out = Pervasives.open_out;

var open_out_bin = Pervasives.open_out_bin;

var open_out_gen = Pervasives.open_out_gen;

var flush = Pervasives.flush;

var flush_all = Pervasives.flush_all;

var output_char = Pervasives.output_char;

var output_string = Pervasives.output_string;

var output_bytes = Pervasives.output_bytes;

var output = Pervasives.output;

var output_substring = Pervasives.output_substring;

var output_byte = Pervasives.output_byte;

var output_binary_int = Pervasives.output_binary_int;

var output_value = Pervasives.output_value;

var seek_out = Pervasives.seek_out;

var pos_out = Pervasives.pos_out;

var out_channel_length = Pervasives.out_channel_length;

var close_out = Pervasives.close_out;

var close_out_noerr = Pervasives.close_out_noerr;

var set_binary_mode_out = Pervasives.set_binary_mode_out;

var open_in = Pervasives.open_in;

var open_in_bin = Pervasives.open_in_bin;

var open_in_gen = Pervasives.open_in_gen;

var input_char = Pervasives.input_char;

var input_line = Pervasives.input_line;

var input = Pervasives.input;

var really_input = Pervasives.really_input;

var really_input_string = Pervasives.really_input_string;

var input_byte = Pervasives.input_byte;

var input_binary_int = Pervasives.input_binary_int;

var input_value = Pervasives.input_value;

var seek_in = Pervasives.seek_in;

var pos_in = Pervasives.pos_in;

var in_channel_length = Pervasives.in_channel_length;

var close_in = Pervasives.close_in;

var close_in_noerr = Pervasives.close_in_noerr;

var set_binary_mode_in = Pervasives.set_binary_mode_in;

var LargeFile = Pervasives.LargeFile;

var string_of_format = Pervasives.string_of_format;

var exit = Pervasives.exit;

var at_exit = Pervasives.at_exit;

var valid_float_lexem = Pervasives.valid_float_lexem;

var unsafe_really_input = Pervasives.unsafe_really_input;

var do_at_exit = Pervasives.do_at_exit;

export {
  List ,
  Queue ,
  invalid_arg ,
  failwith ,
  Exit ,
  abs ,
  max_int ,
  min_int ,
  lnot ,
  infinity ,
  neg_infinity ,
  max_float ,
  min_float ,
  epsilon_float ,
  classify_float ,
  char_of_int ,
  string_of_bool ,
  bool_of_string ,
  bool_of_string_opt ,
  int_of_string_opt ,
  string_of_float ,
  float_of_string_opt ,
  $at ,
  stdin ,
  stdout ,
  stderr ,
  print_char ,
  print_string ,
  print_bytes ,
  print_int ,
  print_float ,
  print_newline ,
  prerr_char ,
  prerr_string ,
  prerr_bytes ,
  prerr_int ,
  prerr_float ,
  prerr_newline ,
  read_line ,
  read_int ,
  read_int_opt ,
  read_float ,
  read_float_opt ,
  open_out ,
  open_out_bin ,
  open_out_gen ,
  flush ,
  flush_all ,
  output_char ,
  output_string ,
  output_bytes ,
  output ,
  output_substring ,
  output_byte ,
  output_binary_int ,
  output_value ,
  seek_out ,
  pos_out ,
  out_channel_length ,
  close_out ,
  close_out_noerr ,
  set_binary_mode_out ,
  open_in ,
  open_in_bin ,
  open_in_gen ,
  input_char ,
  input_line ,
  input ,
  really_input ,
  really_input_string ,
  input_byte ,
  input_binary_int ,
  input_value ,
  seek_in ,
  pos_in ,
  in_channel_length ,
  close_in ,
  close_in_noerr ,
  set_binary_mode_in ,
  LargeFile ,
  string_of_format ,
  exit ,
  at_exit ,
  valid_float_lexem ,
  unsafe_really_input ,
  do_at_exit ,
  
}
/* No side effect */
